name: installer_info
description: A new Flutter plugin.
version: 0.1.0
homepage: https://github.com/caiopo/installer_info
repository: https://github.com/caiopo/installer_info

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.caiopo.installer_info
        pluginClass: InstallerInfoPlugin
      ios:
        pluginClass: InstallerInfoPlugin
